localversion: make a missing version an error in a tarball
When we are compiling and we are not in a git repo, we need to
have a version number already supplied in the source.  If it is
not error out rather than generating a binary with no version.

Signed-off-by: Andy Whitcroft <apw@shadowen.org>
Signed-off-by: Nishanth Aravamudan <nacc@us.ibm.com>

diff --git a/localversion b/localversion
--- a/localversion
+++ b/localversion
@@ -52,9 +52,14 @@ if [ "$?" -eq 0 ]; then
 	fi
 
 else
+	if [ ! -f "$file" ]; then
+		echo 1>&2 "$0: ERROR: unversioned tarball"
+		echo "#error UNVERSIONED tarball" >"$file.h"
+		exit 1
+	fi
+
 	# No version control, use the modification times 
 	# of the source.
-
 	for s in "$@"
 	do
 		if [ "$s" -nt "$file" ]; then
